#!/usr/bin/python3
#
# pull-lp-udebs -- pull udeb package files for ubuntu
# Basic usage: pull-lp-udebs <package name> [version|release]
#
# See pull-pkg

from ubuntutools.pullpkg import PullPkg

if __name__ == "__main__":
    PullPkg.main(distro="ubuntu", pull="udebs")
