#!/usr/bin/python3
#
# pull-debian-source -- pull source package files for debian
# Basic usage: pull-debian-source <package name> [version|release]
#
# See pull-pkg

# pylint: disable=invalid-name
# pylint: enable=invalid-name

from ubuntutools.pullpkg import PullPkg

if __name__ == "__main__":
    PullPkg.main(distro="debian", pull="source")
