#!/usr/bin/python3
#
# pull-uca-udebs -- pull udeb package files for ubuntu cloud archive
# Basic usage: pull-uca-udebs <package name> [version|release]
#
# See pull-pkg

from ubuntutools.pullpkg import PullPkg

if __name__ == "__main__":
    PullPkg.main(distro="uca", pull="udebs")
